/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as GameRouteImport } from './routes/game'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BinaryTetrisRouteImport } from './routes/binary-tetris'
import { Route as BinaryGameRouteImport } from './routes/binary-game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsUnitIdRouteImport } from './routes/units/$unitId'
import { Route as Cs3UnitIdRouteImport } from './routes/cs3/$unitId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BinaryTetrisRoute = BinaryTetrisRouteImport.update({
  id: '/binary-tetris',
  path: '/binary-tetris',
  getParentRoute: () => rootRouteImport,
} as any)
const BinaryGameRoute = BinaryGameRouteImport.update({
  id: '/binary-game',
  path: '/binary-game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsUnitIdRoute = UnitsUnitIdRouteImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const Cs3UnitIdRoute = Cs3UnitIdRouteImport.update({
  id: '/cs3/$unitId',
  path: '/cs3/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/binary-game': typeof BinaryGameRoute
  '/binary-tetris': typeof BinaryTetrisRoute
  '/contact': typeof ContactRoute
  '/game': typeof GameRoute
  '/terms': typeof TermsRoute
  '/cs3/$unitId': typeof Cs3UnitIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/binary-game': typeof BinaryGameRoute
  '/binary-tetris': typeof BinaryTetrisRoute
  '/contact': typeof ContactRoute
  '/game': typeof GameRoute
  '/terms': typeof TermsRoute
  '/cs3/$unitId': typeof Cs3UnitIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/binary-game': typeof BinaryGameRoute
  '/binary-tetris': typeof BinaryTetrisRoute
  '/contact': typeof ContactRoute
  '/game': typeof GameRoute
  '/terms': typeof TermsRoute
  '/cs3/$unitId': typeof Cs3UnitIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/binary-game'
    | '/binary-tetris'
    | '/contact'
    | '/game'
    | '/terms'
    | '/cs3/$unitId'
    | '/units/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/binary-game'
    | '/binary-tetris'
    | '/contact'
    | '/game'
    | '/terms'
    | '/cs3/$unitId'
    | '/units/$unitId'
  id:
    | '__root__'
    | '/'
    | '/binary-game'
    | '/binary-tetris'
    | '/contact'
    | '/game'
    | '/terms'
    | '/cs3/$unitId'
    | '/units/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BinaryGameRoute: typeof BinaryGameRoute
  BinaryTetrisRoute: typeof BinaryTetrisRoute
  ContactRoute: typeof ContactRoute
  GameRoute: typeof GameRoute
  TermsRoute: typeof TermsRoute
  Cs3UnitIdRoute: typeof Cs3UnitIdRoute
  UnitsUnitIdRoute: typeof UnitsUnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binary-tetris': {
      id: '/binary-tetris'
      path: '/binary-tetris'
      fullPath: '/binary-tetris'
      preLoaderRoute: typeof BinaryTetrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binary-game': {
      id: '/binary-game'
      path: '/binary-game'
      fullPath: '/binary-game'
      preLoaderRoute: typeof BinaryGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$unitId': {
      id: '/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof UnitsUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs3/$unitId': {
      id: '/cs3/$unitId'
      path: '/cs3/$unitId'
      fullPath: '/cs3/$unitId'
      preLoaderRoute: typeof Cs3UnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BinaryGameRoute: BinaryGameRoute,
  BinaryTetrisRoute: BinaryTetrisRoute,
  ContactRoute: ContactRoute,
  GameRoute: GameRoute,
  TermsRoute: TermsRoute,
  Cs3UnitIdRoute: Cs3UnitIdRoute,
  UnitsUnitIdRoute: UnitsUnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
